/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/guest/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đổi mã QR lấy phiên bàn
         * @description Xác minh chữ ký Ed25519 của `qrToken`, kiểm tra bàn tồn tại, chi nhánh đang mở cửa,
         *     và (nếu bàn bật QR xoay vòng) kiểm TOTP. Trả về phiên bàn gắn với `deviceId`.
         *
         *     Khi bàn đã có phiên đang hoạt động, hành vi phụ thuộc tình huống — xem `EC-02`:
         *     thiết bị cùng nhóm được **tham gia** phiên hiện có (`201` với `joined: true`);
         *     nghi ngờ là nhóm khách mới thì trả `409 TABLE_SESSION_CONFLICT` để chuyển sang nhân viên.
         */
        post: operations["startTableSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/by-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mở phiên bằng mã bàn 6 ký tự
         * @description Đường dự phòng khi camera không quét được QR. Giới hạn 5 lần thử / 10 phút / IP.
         */
        post: operations["startTableSessionByCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trạng thái phiên hiện tại
         * @description Trả về phiên bàn gắn với token khách hiện tại nếu phiên còn hiệu lực.
         */
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thực đơn của chi nhánh trong phiên
         * @description Trả về toàn bộ thực đơn đang phát hành, kèm trạng thái còn/hết theo thời gian thực.
         *     Đáp ứng có `ETag`; client gửi `If-None-Match` để nhận `304` — đây là đường đi
         *     chịu tải lớn nhất hệ thống, xem `NFR-PERF-01`.
         */
        get: operations["getMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết một món
         * @description Trả chi tiết món trong thực đơn của đúng chi nhánh thuộc phiên bàn hiện tại.
         */
        get: operations["getMenuItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Các đơn trong phiên hiện tại
         * @description Liệt kê các đơn và tổng tiền thuộc đúng phiên bàn hiện tại.
         */
        get: operations["listSessionOrders"];
        put?: never;
        /**
         * Đặt món
         * @description **Điểm nhạy cảm nhất của toàn bộ hợp đồng.**
         *
         *     Client chỉ gửi định danh và số lượng. Máy chủ tính lại toàn bộ giá, phụ phí, thuế
         *     và giảm giá từ catalog trong cùng một giao dịch. Lược đồ request đặt
         *     `additionalProperties: false`, nên mọi trường lạ — đặc biệt là trường giá —
         *     bị từ chối ngay ở tầng xác thực.
         *
         *     `Idempotency-Key` là **bắt buộc**. Gửi lại cùng khoá trong 24 giờ trả về đúng đơn cũ
         *     kèm `200` thay vì tạo đơn mới. Đây là lớp bảo vệ chống chạm hai lần và chống thử lại
         *     sau khi mất mạng.
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết một đơn
         * @description Kiểm tra quyền sở hữu ở cấp đối tượng: đơn phải thuộc đúng phiên đang gọi.
         *     Không đủ điều kiện thì trả `404`, **không** trả `403` — tránh xác nhận sự tồn tại
         *     của đơn thuộc bàn khác.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Khách tự huỷ đơn
         * @description Chỉ chấp nhận khi đơn còn ở `PENDING`. Từ `PREPARING` trở đi phải qua nhân viên.
         */
        post: operations["cancelOrderByGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/staff-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gọi nhân viên
         * @description Giới hạn 1 lần / 90 giây / bàn để chống spam.
         */
        post: operations["callStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/payments/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo ý định thanh toán
         * @description Tạo `PaymentIntent` **trước** khi chuyển hướng sang cổng thanh toán. Bắt buộc
         *     `Idempotency-Key`, vì đây chính là điểm mà `EC-01` xảy ra: khách mất mạng sau khi
         *     tiền đã bị trừ nhưng trước khi trình duyệt quay lại.
         *
         *     Trạng thái thanh toán **không bao giờ** được quyết định bởi URL trả về của trình duyệt.
         */
        post: operations["createPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/payments/intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra trạng thái thanh toán
         * @description Client dò kết quả mỗi 3 giây, tối đa 2 phút, trong lúc hiển thị
         *     "Đang xác nhận thanh toán…". Đây là đường phục hồi phía khách của `EC-01`;
         *     đường phục hồi phía máy chủ là tác vụ đối soát `FR-PAY-06`.
         */
        get: operations["getPaymentIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gợi ý món
         * @description Chạy bằng mô hình thống kê cục bộ trên CPU, **không** phụ thuộc nhà cung cấp LLM
         *     bên ngoài — nên endpoint này vẫn hoạt động khi mạng ra Internet chết, xem `EC-05`.
         *     Trường `source` cho client biết đang nhận gợi ý từ mô hình hay từ danh sách dự phòng.
         */
        get: operations["getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/assistant/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gửi tin nhắn cho trợ lý thực đơn (SSE)
         * @description Đáp ứng dạng `text/event-stream` để đạt `NFR-PERF-05`. Backend gọi AI service,
         *     AI service gọi Claude API. Khoá API chỉ tồn tại phía máy chủ — trình duyệt
         *     **không bao giờ** gọi thẳng nhà cung cấp, xem `NFR-AI-02`.
         *
         *     Giới hạn 512 token vào / 512 token ra mỗi lượt, 20 lượt mỗi phiên,
         *     6 tin nhắn mỗi phút — `NFR-SEC-19`.
         */
        post: operations["sendAssistantMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/kds/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hàng đợi pha chế
         * @description Tải trạng thái ban đầu. Cập nhật sau đó đến qua WebSocket — xem `asyncapi.yaml`,
         *     kênh `kds/{storeId}`. KDS lưu kết quả này để chạy được ở chế độ ngoại tuyến (`FR-BAR-06`).
         */
        get: operations["getKdsQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/order-lines/{lineId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Đổi trạng thái một món
         * @description Dùng **khoá lạc quan**: client gửi `If-Match` mang `version` đã đọc. Lệch phiên bản
         *     trả `409` kèm trạng thái hiện thời để client tự làm mới — đây là cách `EC-06` được
         *     xử lý ở tầng hợp đồng.
         *
         *     Chuyển đổi không hợp lệ theo máy trạng thái trả `422 INVALID_TRANSITION`,
         *     kể cả khi phiên bản còn khớp.
         */
        patch: operations["updateOrderLineStatus"];
        trace?: never;
    };
    "/api/v1/staff/ingredients/{ingredientId}/sold-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Báo hết nguyên liệu
         * @description Ẩn mọi món dùng nguyên liệu này khỏi thực đơn khách trong ≤ 2 giây, và phát
         *     sự kiện cảnh báo cho các đơn đang chờ có chứa món bị ảnh hưởng — `EC-04`.
         */
        post: operations["markIngredientSoldOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sơ đồ bàn theo trạng thái
         * @description Trả trạng thái các bàn thuộc những chi nhánh nằm trong phạm vi phiên nhân viên.
         */
        get: operations["listTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/tables/{tableId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đóng bàn
         * @description Đóng bàn khi còn hoá đơn chưa thanh toán bắt buộc có `reason`. Lý do
         *     `GUEST_LEFT_UNPAID` tạo bản ghi thất thoát cho báo cáo tuần — `EC-07`.
         */
        post: operations["closeTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders/{orderId}/payments/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xác nhận thu tiền mặt
         * @description Nếu hoá đơn đang có ý định thanh toán trực tuyến ở `AUTHORIZING`, máy chủ vẫn
         *     cho phép nhưng đánh dấu giao dịch là có rủi ro trùng và bật cảnh báo — `EC-08`.
         *     Ràng buộc duy nhất ở tầng CSDL bảo đảm mỗi hoá đơn chỉ có tối đa một giao dịch `SETTLED`.
         */
        post: operations["confirmCashPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập nhân viên
         * @description Token đặt trong cookie `HttpOnly; Secure; SameSite=Strict; Path=/api`.
         *     **Không** trả token trong body — `localStorage` bị XSS đọc được, xem `NFR-SEC-05`.
         *     Thông báo lỗi không tiết lộ email có tồn tại hay không.
         */
        post: operations["staffLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xoay vòng token
         * @description Áp dụng xoay vòng có phát hiện tái sử dụng: dùng lại một refresh token đã tiêu
         *     sẽ **thu hồi toàn bộ chuỗi token** của người dùng đó và phát cảnh báo bảo mật —
         *     `NFR-SEC-04`.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/payments/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Nhận callback từ cổng thanh toán
         * @description **Nguồn sự thật duy nhất về trạng thái thanh toán.**
         *
         *     Chữ ký HMAC được xác minh **trước khi** phân tích nội dung. Chống phát lại bằng
         *     `nonce` và cửa sổ thời gian. Xử lý idempotent: cùng một sự kiện gửi nhiều lần
         *     chỉ có tác dụng một lần.
         *
         *     Nếu sự kiện thành công đến sau khi hoá đơn đã `SETTLED` bằng tiền mặt, hệ thống
         *     **không** từ chối im lặng mà tạo `Refund` chờ duyệt gắn nhãn `DUPLICATE_PAYMENT` — `EC-08`.
         */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 kèm hai phần mở rộng bắt buộc của QROS. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            /**
             * @description Thông điệp cho người dùng cuối. **Không bao giờ** chứa stack trace,
             *     câu truy vấn, hay chi tiết nội bộ — `NFR-SEC` A05.
             */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /**
             * @description Mã ổn định để máy đọc, ví dụ `PRICE_NOT_ACCEPTED`.
             * @example PRICE_NOT_ACCEPTED
             * @example ITEM_SOLD_OUT
             * @example INVALID_TRANSITION
             */
            code: string;
            /** @description Tương quan với truy vết OpenTelemetry để nhân viên tra cứu. */
            traceId: string;
        };
        PriceChangedProblem: components["schemas"]["Problem"] & {
            currentTotal?: components["schemas"]["Money"];
            changedLines?: {
                /** Format: uuid */
                menuItemId?: string;
                oldUnitPrice?: components["schemas"]["Money"];
                newUnitPrice?: components["schemas"]["Money"];
            }[];
        };
        /**
         * @description Tiền luôn là **số nguyên đơn vị đồng**. Không dùng số thực ở bất kỳ đâu
         *     trong hệ thống, kể cả khi hiển thị.
         */
        Money: {
            /**
             * Format: int64
             * @example 55000
             */
            amount: number;
            /** @enum {string} */
            currency: "VND";
        };
        StartSessionRequest: {
            /** @description JWS Ed25519 đọc từ mã QR trên mặt bàn. */
            qrToken: string;
            /**
             * Format: uuid
             * @description UUID sinh phía client, lưu lâu dài trong trình duyệt.
             */
            deviceId: string;
            /** @description Biệt danh hiển thị khi nhiều thiết bị chung một bàn. */
            nickname?: string;
            /** @description Tuỳ chọn, chỉ gửi khi khách cấp quyền vị trí. Chỉ dùng làm tín hiệu phụ. */
            coords?: {
                lat?: number;
                lon?: number;
            };
        };
        StartSessionByCodeRequest: {
            tableCode: string;
            /** Format: uuid */
            deviceId: string;
            nickname?: string;
        };
        TableSession: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            storeId: string;
            storeName?: string;
            /** Format: uuid */
            tableId: string;
            /** @example A-04 */
            tableLabel: string;
            zoneName?: string;
            /** @description JWS phiên bàn. Client đính kèm ở header `Authorization`. */
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description `true` nếu thiết bị tham gia một phiên đã có sẵn — xem `EC-02`. */
            joined: boolean;
            /** @description Biệt danh các thiết bị trong phiên. Không chứa dữ liệu cá nhân. */
            participants?: {
                nickname?: string;
                isSelf?: boolean;
            }[];
        };
        Menu: {
            /** Format: uuid */
            storeId: string;
            /** Format: date-time */
            updatedAt: string;
            categories: {
                /** Format: uuid */
                id: string;
                name: string;
                displayOrder?: number;
                items: components["schemas"]["MenuItem"][];
            }[];
        };
        MenuItem: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** Format: uri */
            imageUrl?: string;
            basePrice: components["schemas"]["Money"];
            /** @description Cập nhật realtime khi barista báo hết nguyên liệu — `FR-BAR-05`. */
            available: boolean;
            /** @description Nhãn cảnh báo dị ứng. Sai ở đây là rủi ro sức khoẻ, không phải lỗi hiển thị. */
            allergens?: ("MILK" | "PEANUT" | "GLUTEN" | "SOY" | "EGG" | "NUTS")[];
            attributes?: ("DAIRY_FREE" | "CAFFEINE_FREE" | "LOW_SUGAR" | "VEGAN" | "HOT" | "COLD")[];
            variants: {
                /** Format: uuid */
                id: string;
                /** @example Size L */
                name: string;
                price: components["schemas"]["Money"];
                available?: boolean;
            }[];
            optionGroups?: components["schemas"]["OptionGroup"][];
        };
        OptionGroup: {
            /** Format: uuid */
            id: string;
            /** @example Mức đường */
            name: string;
            /** @enum {string} */
            selection: "SINGLE" | "MULTIPLE";
            required?: boolean;
            minSelect?: number;
            maxSelect?: number;
            options: {
                /** Format: uuid */
                id: string;
                /** @example 50% */
                name: string;
                surcharge: components["schemas"]["Money"];
                available?: boolean;
            }[];
        };
        /**
         * @description ⚠ `additionalProperties: false` ở đây và ở `CreateOrderLine` là biện pháp cưỡng chế
         *     `ADR-06` tại tầng hợp đồng. Không được nới lỏng trong bất kỳ hoàn cảnh nào.
         */
        CreateOrderRequest: {
            /** @description Tối đa 8 món mỗi đơn — hạn mức chống lạm dụng, lớp 7 mục 5.3.2. */
            lines: components["schemas"]["CreateOrderLine"][];
            note?: string;
        };
        CreateOrderLine: {
            /** Format: uuid */
            menuItemId: string;
            /** Format: uuid */
            variantId: string;
            optionIds?: string[];
            quantity: number;
            /**
             * @description Văn bản tự do do khách nhập. Được làm sạch trước khi hiển thị trên KDS,
             *     và coi là **dữ liệu không tin cậy** nếu lọt vào ngữ cảnh trợ lý — `NFR-SEC-16`.
             */
            note?: string;
            addedBy?: string;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /**
             * @description Mã ngắn hiển thị cho khách và barista.
             * @example A04-17
             */
            shortCode?: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "SERVED" | "COMPLETED" | "CANCELLED" | "EXPIRED";
            lines: components["schemas"]["OrderLine"][];
            subtotal?: components["schemas"]["Money"];
            discount?: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            /** Format: date-time */
            placedAt: string;
            /**
             * Format: date-time
             * @description Tính theo độ dài hàng đợi hiện tại — `FR-CUS-10`.
             */
            estimatedReadyAt?: string;
            /** @description `true` cho đơn đầu tiên của phiên lạ — cổng xác nhận ở `EC-03`. */
            requiresStaffConfirmation?: boolean;
            version: number;
        };
        OrderLine: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            menuItemId: string;
            name: string;
            variantName?: string;
            /**
             * @example [
             *       "Đường 50%",
             *       "Ít đá",
             *       "Thêm trân châu"
             *     ]
             */
            optionNames?: string[];
            quantity: number;
            /** @description Chỉ có ở **đáp ứng**. Không bao giờ chấp nhận ở request. */
            unitPrice?: components["schemas"]["Money"];
            lineTotal: components["schemas"]["Money"];
            note?: string;
            addedBy?: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "SERVED" | "CANCELLED";
            /** @description Dùng cho khoá lạc quan qua `If-Match` — `EC-06`. */
            version: number;
        };
        KdsTicket: {
            /** Format: uuid */
            orderId: string;
            shortCode: string;
            tableLabel: string;
            /** Format: date-time */
            placedAt: string;
            /** @description Ngưỡng cảnh báo, mặc định 480 giây — `FR-BAR-04`. */
            slaSeconds: number;
            isOverdue?: boolean;
            lines: components["schemas"]["OrderLine"][];
        };
        TableState: {
            /** Format: uuid */
            tableId: string;
            label: string;
            zoneName?: string;
            /** @enum {string} */
            status: "AVAILABLE" | "OCCUPIED" | "AWAITING_PAYMENT" | "CLEANING" | "DISABLED";
            /** Format: date-time */
            openedAt?: string;
            unpaidTotal?: components["schemas"]["Money"];
            /** @description Vượt 45 phút mà còn dư nợ thì hiện cảnh báo — `EC-07`. */
            idleMinutes?: number;
        };
        CreatePaymentIntentRequest: {
            /** @enum {string} */
            method: "CASH" | "VNPAY" | "MOMO" | "ZALOPAY";
            /** @description Bỏ trống để thanh toán toàn bộ hoá đơn của phiên. */
            orderIds?: string[];
            /**
             * Format: uri
             * @description Chỉ để đưa khách trở lại giao diện. **Không** được dùng làm căn cứ xác định
             *     trạng thái thanh toán — xem `EC-01`.
             */
            returnUrl?: string;
        };
        PaymentIntent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "CREATED" | "AUTHORIZING" | "AUTHORIZED" | "SETTLED" | "FAILED" | "VOIDED" | "EXPIRED";
            amount: components["schemas"]["Money"];
            method: string;
            /**
             * Format: uri
             * @description Nơi chuyển hướng khách sang cổng thanh toán.
             */
            redirectUrl?: string;
            /**
             * Format: date-time
             * @description Quá 15 phút không có kết luận thì chuyển `EXPIRED` — `EC-01`.
             */
            expiresAt?: string;
            /** @description Mã tham chiếu để thu ngân đối soát tay khi cần. */
            reference?: string;
        };
        CashPaymentResult: {
            /** Format: uuid */
            orderId: string;
            settled: boolean;
            change: components["schemas"]["Money"];
            /** @description `true` nếu tồn tại ý định thanh toán trực tuyến đang chờ — `EC-08`. */
            duplicateWarning?: boolean;
        };
        RecommendationList: {
            /**
             * @description `RULE_BASED_FALLBACK` khi mô hình chưa đủ dữ liệu (`FR-AI-02`) hoặc đang suy giảm.
             *     Client đổi tiêu đề khối từ "Gợi ý cho bạn" thành "Món bán chạy hôm nay" —
             *     không hiển thị lỗi kỹ thuật cho khách.
             * @enum {string}
             */
            source: "MODEL" | "RULE_BASED_FALLBACK";
            items: {
                /** Format: uuid */
                menuItemId: string;
                name: string;
                price?: components["schemas"]["Money"];
                /** @description Lý do hiển thị cho khách, ví dụ "Thường được gọi kèm". */
                reason: string;
            }[];
        };
    };
    responses: {
        /** @description Lỗi theo RFC 7807. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Vượt hạn mức. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description UUIDv4. Lưu 24 giờ. Gửi lại cùng khoá trả về kết quả cũ. */
        IdempotencyKey: string;
        OrderId: string;
        ItemId: string;
        TableId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startTableSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Phiên đã được tạo hoặc đã tham gia phiên sẵn có. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSession"];
                };
            };
            /** @description `QR_INVALID_SIGNATURE` · `QR_OTP_EXPIRED` */
            401: components["responses"]["Problem"];
            /** @description `STORE_CLOSED` · bàn ở trạng thái `DISABLED` */
            403: components["responses"]["Problem"];
            /** @description `TABLE_SESSION_CONFLICT` — cần nhân viên xử lý. */
            409: components["responses"]["Problem"];
            429: components["responses"]["RateLimited"];
        };
    };
    startTableSessionByCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionByCodeRequest"];
            };
        };
        responses: {
            /** @description Phiên đã được tạo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSession"];
                };
            };
            /** @description `TABLE_CODE_INVALID` */
            401: components["responses"]["Problem"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSession"];
                };
            };
            /** @description `TABLE_SESSION_EXPIRED` — cần quét lại QR. */
            401: components["responses"]["Problem"];
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
            /** @description Thực đơn chưa đổi. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    getMenuItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listSessionOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders: components["schemas"]["Order"][];
                        sessionTotal: components["schemas"]["Money"];
                        /** @enum {string} */
                        paymentStatus?: "UNPAID" | "PENDING_CASH" | "AUTHORIZING" | "SETTLED";
                    };
                };
            };
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description UUIDv4. Lưu 24 giờ. Gửi lại cùng khoá trả về kết quả cũ. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Khoá idempotency đã dùng — trả lại đơn đã tạo trước đó. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Đơn đã được tạo. */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /**
             * @description `PRICE_NOT_ACCEPTED` — client gửi kèm trường giá.
             *     `VALIDATION_FAILED` — payload sai lược đồ.
             */
            400: components["responses"]["Problem"];
            /**
             * @description `PRICE_CHANGED` — giá đổi giữa lúc xem và lúc đặt; phần mở rộng `currentTotal`
             *     chứa bảng giá mới để client hiển thị xác nhận lại.
             *     `ITEM_SOLD_OUT` — món vừa hết.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["PriceChangedProblem"];
                };
            };
            /** @description `ORDER_RATE_LIMITED` — vượt hạn mức 3 đơn / 5 phút / phiên. */
            429: components["responses"]["RateLimited"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    cancelOrderByGuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã huỷ. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description `INVALID_TRANSITION` — đơn đã rời khỏi `PENDING`. */
            422: components["responses"]["Problem"];
        };
    };
    callStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason: "REFILL_WATER" | "CLEAN_TABLE" | "PAYMENT_HELP" | "OTHER";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Đã chuyển tới nhân viên. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    createPaymentIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description UUIDv4. Lưu 24 giờ. Gửi lại cùng khoá trả về kết quả cũ. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentIntentRequest"];
            };
        };
        responses: {
            /** @description Ý định đã tạo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            /** @description `PAYMENT_ALREADY_SETTLED` — hoá đơn đã thanh toán, xem `EC-08`. */
            409: components["responses"]["Problem"];
        };
    };
    getPaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getRecommendations: {
        parameters: {
            query?: {
                context?: "MENU_BROWSE" | "CART_REVIEW";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
        };
    };
    sendAssistantMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    /** Format: uuid */
                    conversationId?: string;
                };
            };
        };
        responses: {
            /**
             * @description Luồng SSE. Các loại sự kiện: `token`, `tool_call`, `done`, `error`.
             *     `tool_call` chỉ mang một trong bốn hàm cho phép ở `FR-AI-04`, và
             *     `add_to_cart` luôn cần khách xác nhận bằng một thao tác chạm.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description `ASSISTANT_RATE_LIMITED` */
            429: components["responses"]["RateLimited"];
            /**
             * @description `AI_UNAVAILABLE` — nhà cung cấp gián đoạn, bị chặn tần suất, hoặc chi nhánh
             *     đã chạm trần ngân sách. Client chuyển sang khối FAQ tĩnh, xem `EC-05`.
             */
            503: components["responses"]["Problem"];
        };
    };
    getKdsQueue: {
        parameters: {
            query?: {
                /** @description Lọc theo trạm pha chế. */
                station?: "COFFEE" | "TEA" | "FOOD" | "ALL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tickets: components["schemas"]["KdsTicket"][];
                        /**
                         * Format: date-time
                         * @description Để KDS tính bộ đếm SLA mà không phụ thuộc đồng hồ máy khách.
                         */
                        serverTime: string;
                    };
                };
            };
        };
    };
    updateOrderLineStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Giá trị `version` của dòng đơn mà client đang thấy. */
                "If-Match": string;
            };
            path: {
                lineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "PREPARING" | "READY" | "SERVED" | "CANCELLED";
                    /** @description Bắt buộc khi `status = CANCELLED`. */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Đã cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderLine"];
                };
            };
            /** @description `VERSION_CONFLICT` — người khác vừa cập nhật; phần mở rộng `current` chứa bản mới nhất. */
            409: components["responses"]["Problem"];
            /** @description `INVALID_TRANSITION` */
            422: components["responses"]["Problem"];
        };
    };
    markIngredientSoldOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã cập nhật. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        affectedItemIds?: string[];
                        affectedOpenOrderIds?: string[];
                    };
                };
            };
        };
    };
    listTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableState"][];
                };
            };
        };
    };
    closeTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: components["parameters"]["TableId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason?: "PAID_CASH_UNRECORDED" | "GUEST_LEFT_UNPAID" | "SYSTEM_ERROR" | "OTHER";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Bàn đã đóng. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableState"];
                };
            };
            /** @description `REASON_REQUIRED` — còn dư nợ nhưng thiếu lý do. */
            422: components["responses"]["Problem"];
        };
    };
    confirmCashPayment: {
        parameters: {
            query?: never;
            header: {
                /** @description UUIDv4. Lưu 24 giờ. Gửi lại cùng khoá trả về kết quả cũ. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tendered: components["schemas"]["Money"];
                    /**
                     * @description Phải là `true` nếu hoá đơn đang chờ kết quả thanh toán ví. Buộc thu ngân
                     *     xác nhận có chủ đích thay vì bấm qua theo quán tính.
                     */
                    acknowledgeOnlinePending: boolean;
                };
            };
        };
        responses: {
            /** @description Đã ghi nhận. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashPaymentResult"];
                };
            };
            /** @description `PAYMENT_ALREADY_SETTLED` */
            409: components["responses"]["Problem"];
        };
    };
    staffLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @description Bắt buộc với `STORE_MANAGER` và `ADMIN`. */
                    totp?: string;
                };
            };
        };
        responses: {
            /** @description Đăng nhập thành công; token nằm trong cookie. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `INVALID_CREDENTIALS` — cùng một thông điệp cho mọi nguyên nhân. */
            401: components["responses"]["Problem"];
            /** @description `ACCOUNT_LOCKED` — 5 lần sai trong 15 phút. */
            423: components["responses"]["Problem"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã cấp token mới. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `REFRESH_REUSED` — phát hiện tái sử dụng, toàn bộ chuỗi đã bị thu hồi. */
            401: components["responses"]["Problem"];
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Signature": string;
                "X-Timestamp": string;
            };
            path: {
                provider: "vnpay" | "momo" | "zalopay";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Đã tiếp nhận. Luôn trả về nhanh; xử lý nặng đẩy sang hàng đợi. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `WEBHOOK_SIGNATURE_INVALID` */
            401: components["responses"]["Problem"];
        };
    };
}
