# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Problem(BaseModel):
    """
    RFC 7807 kèm hai phần mở rộng bắt buộc của QROS.
    """

    type: AnyUrl
    title: str
    status: int
    detail: str | None = Field(
        None,
        description='Thông điệp cho người dùng cuối. **Không bao giờ** chứa stack trace,\ncâu truy vấn, hay chi tiết nội bộ — `NFR-SEC` A05.\n',
    )
    instance: str | None = None
    code: str = Field(
        ...,
        description='Mã ổn định để máy đọc, ví dụ `PRICE_NOT_ACCEPTED`.',
        examples=['PRICE_NOT_ACCEPTED', 'ITEM_SOLD_OUT', 'INVALID_TRANSITION'],
    )
    traceId: str = Field(
        ..., description='Tương quan với truy vết OpenTelemetry để nhân viên tra cứu.'
    )


class Currency(StrEnum):
    VND = 'VND'


class Money(BaseModel):
    """
    Tiền luôn là **số nguyên đơn vị đồng**. Không dùng số thực ở bất kỳ đâu
    trong hệ thống, kể cả khi hiển thị.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    amount: int = Field(..., examples=[55000])
    currency: Currency


class Coords(BaseModel):
    """
    Tuỳ chọn, chỉ gửi khi khách cấp quyền vị trí. Chỉ dùng làm tín hiệu phụ.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    lat: float | None = None
    lon: float | None = None


class StartSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    qrToken: str = Field(..., description='JWS Ed25519 đọc từ mã QR trên mặt bàn.')
    deviceId: UUID = Field(
        ..., description='UUID sinh phía client, lưu lâu dài trong trình duyệt.'
    )
    nickname: str | None = Field(
        None,
        description='Biệt danh hiển thị khi nhiều thiết bị chung một bàn.',
        max_length=24,
    )
    coords: Coords | None = Field(
        None,
        description='Tuỳ chọn, chỉ gửi khi khách cấp quyền vị trí. Chỉ dùng làm tín hiệu phụ.',
    )


class StartSessionByCodeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tableCode: str = Field(..., pattern='^[A-Z0-9]{6}$')
    deviceId: UUID
    nickname: str | None = Field(None, max_length=24)


class Participant(BaseModel):
    nickname: str | None = None
    isSelf: bool | None = None


class TableSession(BaseModel):
    sessionId: UUID
    storeId: UUID
    storeName: str | None = None
    tableId: UUID
    tableLabel: str = Field(..., examples=['A-04'])
    zoneName: str | None = None
    accessToken: str = Field(
        ..., description='JWS phiên bàn. Client đính kèm ở header `Authorization`.'
    )
    expiresAt: AwareDatetime
    joined: bool = Field(
        ...,
        description='`true` nếu thiết bị tham gia một phiên đã có sẵn — xem `EC-02`.',
    )
    participants: list[Participant] | None = Field(
        None,
        description='Biệt danh các thiết bị trong phiên. Không chứa dữ liệu cá nhân.',
    )


class Allergen(StrEnum):
    MILK = 'MILK'
    PEANUT = 'PEANUT'
    GLUTEN = 'GLUTEN'
    SOY = 'SOY'
    EGG = 'EGG'
    NUTS = 'NUTS'


class Attribute(StrEnum):
    DAIRY_FREE = 'DAIRY_FREE'
    CAFFEINE_FREE = 'CAFFEINE_FREE'
    LOW_SUGAR = 'LOW_SUGAR'
    VEGAN = 'VEGAN'
    HOT = 'HOT'
    COLD = 'COLD'


class Variant(BaseModel):
    id: UUID
    name: str = Field(..., examples=['Size L'])
    price: Money
    available: bool | None = None


class Selection(StrEnum):
    SINGLE = 'SINGLE'
    MULTIPLE = 'MULTIPLE'


class Option(BaseModel):
    id: UUID
    name: str = Field(..., examples=['50%'])
    surcharge: Money
    available: bool | None = None


class OptionGroup(BaseModel):
    id: UUID
    name: str = Field(..., examples=['Mức đường'])
    selection: Selection
    required: bool | None = None
    minSelect: int | None = Field(None, ge=0)
    maxSelect: int | None = Field(None, ge=1)
    options: list[Option]


class CreateOrderLine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    menuItemId: UUID
    variantId: UUID
    optionIds: list[UUID] | None = Field(None, max_length=10)
    quantity: int = Field(..., ge=1, le=20)
    note: str | None = Field(
        None,
        description='Văn bản tự do do khách nhập. Được làm sạch trước khi hiển thị trên KDS,\nvà coi là **dữ liệu không tin cậy** nếu lọt vào ngữ cảnh trợ lý — `NFR-SEC-16`.\n',
        max_length=200,
    )
    addedBy: str | None = Field(None, max_length=24)


class Status(StrEnum):
    PENDING = 'PENDING'
    CONFIRMED = 'CONFIRMED'
    PREPARING = 'PREPARING'
    READY = 'READY'
    SERVED = 'SERVED'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    EXPIRED = 'EXPIRED'


class Status1(StrEnum):
    PENDING = 'PENDING'
    CONFIRMED = 'CONFIRMED'
    PREPARING = 'PREPARING'
    READY = 'READY'
    SERVED = 'SERVED'
    CANCELLED = 'CANCELLED'


class OrderLine(BaseModel):
    id: UUID
    menuItemId: UUID
    name: str
    variantName: str | None = None
    optionNames: list[str] | None = Field(
        None, examples=[['Đường 50%', 'Ít đá', 'Thêm trân châu']]
    )
    quantity: int
    unitPrice: Money | None = Field(
        None, description='Chỉ có ở **đáp ứng**. Không bao giờ chấp nhận ở request.'
    )
    lineTotal: Money
    note: str | None = None
    addedBy: str | None = None
    status: Status1
    version: int = Field(
        ..., description='Dùng cho khoá lạc quan qua `If-Match` — `EC-06`.'
    )


class KdsTicket(BaseModel):
    orderId: UUID
    shortCode: str
    tableLabel: str
    placedAt: AwareDatetime
    slaSeconds: int = Field(
        ..., description='Ngưỡng cảnh báo, mặc định 480 giây — `FR-BAR-04`.'
    )
    isOverdue: bool | None = None
    lines: list[OrderLine]


class Status2(StrEnum):
    AVAILABLE = 'AVAILABLE'
    OCCUPIED = 'OCCUPIED'
    AWAITING_PAYMENT = 'AWAITING_PAYMENT'
    CLEANING = 'CLEANING'
    DISABLED = 'DISABLED'


class TableState(BaseModel):
    tableId: UUID
    label: str
    zoneName: str | None = None
    status: Status2
    openedAt: AwareDatetime | None = None
    unpaidTotal: Money | None = None
    idleMinutes: int | None = Field(
        None, description='Vượt 45 phút mà còn dư nợ thì hiện cảnh báo — `EC-07`.'
    )


class Method(StrEnum):
    CASH = 'CASH'
    VNPAY = 'VNPAY'
    MOMO = 'MOMO'
    ZALOPAY = 'ZALOPAY'


class CreatePaymentIntentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Method
    orderIds: list[UUID] | None = Field(
        None, description='Bỏ trống để thanh toán toàn bộ hoá đơn của phiên.'
    )
    returnUrl: AnyUrl | None = Field(
        None,
        description='Chỉ để đưa khách trở lại giao diện. **Không** được dùng làm căn cứ xác định\ntrạng thái thanh toán — xem `EC-01`.\n',
    )


class Status3(StrEnum):
    CREATED = 'CREATED'
    AUTHORIZING = 'AUTHORIZING'
    AUTHORIZED = 'AUTHORIZED'
    SETTLED = 'SETTLED'
    FAILED = 'FAILED'
    VOIDED = 'VOIDED'
    EXPIRED = 'EXPIRED'


class PaymentIntent(BaseModel):
    id: UUID
    status: Status3
    amount: Money
    method: str
    redirectUrl: AnyUrl | None = Field(
        None, description='Nơi chuyển hướng khách sang cổng thanh toán.'
    )
    expiresAt: AwareDatetime | None = Field(
        None,
        description='Quá 15 phút không có kết luận thì chuyển `EXPIRED` — `EC-01`.',
    )
    reference: str | None = Field(
        None, description='Mã tham chiếu để thu ngân đối soát tay khi cần.'
    )


class CashPaymentResult(BaseModel):
    orderId: UUID
    settled: bool
    change: Money
    duplicateWarning: bool | None = Field(
        None,
        description='`true` nếu tồn tại ý định thanh toán trực tuyến đang chờ — `EC-08`.',
    )


class Source(StrEnum):
    """
    `RULE_BASED_FALLBACK` khi mô hình chưa đủ dữ liệu (`FR-AI-02`) hoặc đang suy giảm.
    Client đổi tiêu đề khối từ "Gợi ý cho bạn" thành "Món bán chạy hôm nay" —
    không hiển thị lỗi kỹ thuật cho khách.

    """

    MODEL = 'MODEL'
    RULE_BASED_FALLBACK = 'RULE_BASED_FALLBACK'


class Item(BaseModel):
    menuItemId: UUID
    name: str
    price: Money | None = None
    reason: str = Field(
        ..., description='Lý do hiển thị cho khách, ví dụ "Thường được gọi kèm".'
    )


class RecommendationList(BaseModel):
    source: Source = Field(
        ...,
        description='`RULE_BASED_FALLBACK` khi mô hình chưa đủ dữ liệu (`FR-AI-02`) hoặc đang suy giảm.\nClient đổi tiêu đề khối từ "Gợi ý cho bạn" thành "Món bán chạy hôm nay" —\nkhông hiển thị lỗi kỹ thuật cho khách.\n',
    )
    items: list[Item]


class ChangedLine(BaseModel):
    menuItemId: UUID | None = None
    oldUnitPrice: Money | None = None
    newUnitPrice: Money | None = None


class PriceChangedProblem(Problem):
    currentTotal: Money | None = None
    changedLines: list[ChangedLine] | None = None


class MenuItem(BaseModel):
    id: UUID
    name: str
    description: str | None = None
    imageUrl: AnyUrl | None = None
    basePrice: Money
    available: bool = Field(
        ...,
        description='Cập nhật realtime khi barista báo hết nguyên liệu — `FR-BAR-05`.',
    )
    allergens: list[Allergen] | None = Field(
        None,
        description='Nhãn cảnh báo dị ứng. Sai ở đây là rủi ro sức khoẻ, không phải lỗi hiển thị.',
    )
    attributes: list[Attribute] | None = None
    variants: list[Variant] = Field(..., min_length=1)
    optionGroups: list[OptionGroup] | None = None


class CreateOrderRequest(BaseModel):
    """
    ⚠ `additionalProperties: false` ở đây và ở `CreateOrderLine` là biện pháp cưỡng chế
    `ADR-06` tại tầng hợp đồng. Không được nới lỏng trong bất kỳ hoàn cảnh nào.

    """

    model_config = ConfigDict(
        extra='forbid',
    )
    lines: list[CreateOrderLine] = Field(
        ...,
        description='Tối đa 8 món mỗi đơn — hạn mức chống lạm dụng, lớp 7 mục 5.3.2.',
        max_length=8,
        min_length=1,
    )
    note: str | None = Field(None, max_length=200)


class Order(BaseModel):
    id: UUID
    shortCode: str | None = Field(
        None, description='Mã ngắn hiển thị cho khách và barista.', examples=['A04-17']
    )
    status: Status
    lines: list[OrderLine]
    subtotal: Money | None = None
    discount: Money | None = None
    total: Money
    placedAt: AwareDatetime
    estimatedReadyAt: AwareDatetime | None = Field(
        None, description='Tính theo độ dài hàng đợi hiện tại — `FR-CUS-10`.'
    )
    requiresStaffConfirmation: bool | None = Field(
        None,
        description='`true` cho đơn đầu tiên của phiên lạ — cổng xác nhận ở `EC-03`.',
    )
    version: int


class Category(BaseModel):
    id: UUID
    name: str
    displayOrder: int | None = None
    items: list[MenuItem]


class Menu(BaseModel):
    storeId: UUID
    updatedAt: AwareDatetime
    categories: list[Category]
